matrix:
  include:
    - language: node_js
      node_js:
        - "6"
      before_install:
        - cd lang/es6
      install:
        - npm install
      script:
        - npm test

    # https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
    - language: go
      go:
        - 1.12.x
      before_script:
        - cd lang/golang
      script:
        - go teset -v -race ./...

notifications:
  email:
    on_success: never
    on_failure: always
