matrix:
  include:
    - language: node_js
      node_js:
        - "6"
        - "8.0.0"
      before_install:
        - cd lang/es6
      install:
        - npm install
      script:
        - npm test

    # https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
    - language: go
      go:
        - 1.12.x
      before_script:
        - cd lang/golang
      script:
        - go test -v -race -coverprofile=cover.out ./...
        # - go tool cover -func=cover.out

    - language: node_js
      node_js:
        - "8.0.0"
      before_install:
        - cd docs
        - npm cache clean --force
        - rm -Rf node_modules/
      install:
        - npm install -g gitbook-cli
        - npm install
      script:
        - gitbook install
        - gitbook build
      branches:
        only:
          - master

notifications:
  email:
    on_success: never
    on_failure: always
